name: Deploy to Railway

on:
  push:
    branches:
      - main  # atau "master", tergantung nama branch kamu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Railway CLI
      run: npm install -g railway

    - name: Login Railway (via Token)
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway up --service web
