name: Deploy to Railway

on:
  push:
    branches:
      - main  # CI/CD akan berjalan otomatis saat kamu push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Mesin yang digunakan GitHub

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3  # Mengambil source code kamu

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Versi Python untuk menjalankan environment

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Railway
      uses: railwayapp/cli-action@v1  # Menggunakan plugin GitHub Action Railway
      with:
        railwayToken: ${{ secrets.RAILWAY_TOKEN }}
